### ISSUE TITLE
Add the category testing

### ISSUE THREAD

**Issue by melMass** [swellaby/vscode-rust-test-adapter#169]
Hi,

Thanks for this extension.
In VSCode, when you go to the testing tab, there is a button that says something like "browse test extensions", this opens the extension tab with the `@category:"testing"` attribute.
My suggestion is just to add the `testing` category 

Thanks

**Comment by calebcartwright** [comment]
Thanks for sharing! I wasn't aware that a testing category existed but agree that'd be more relevant than the current "other".

Any chance you'd be willing to submit a PR? Believe it's just a matter of updating the value for this key:

https://github.com/swellaby/vscode-rust-test-adapter/blob/aa270603368739ff663bd84067a4308b11843c73/package.json#L67-L69
