### ISSUE TITLE
Root test suite not running when root only contains test cases.

### ISSUE THREAD

**Issue by tehstun** [swellaby/vscode-rust-test-adapter#27]
![image](https://user-images.githubusercontent.com/12329422/57809694-e5a57300-775d-11e9-8b93-6bc552b204f1.png)

## Expected Behavior

When pressing the test button to run all tests suites and or test cases within the test explorer, the test explorer will iterate through the test suites and cases and process each one.

## Actual Behavior

When pressing the test button with only test cases in the root, the explorer attempts to extract test suites 'root' and only be returned a list of test caseids. Attempting to get the ITestSuiteNode for a given id returns undefined resulting in the "node.isStructuralNode" check failing.

reference: [extractPackageTestSuitesFromNodes](https://github.com/swellaby/vscode-rust-test-adapter/blob/0d7c1db54ffdc3451f1f2e6a36b2c78d89ba7990/src/rust-adapter.ts#L68)

## Steps to Reproduce the Problem

  1. Create a simple cargo package with no dependencies and just package metadata.
  2. Create a simple test case in main.rs
  1. Attempt to run test case through explorer (run all tests button)

## Specifications

  - Version: 0.5.0
  - Platform: Windows + wsl
  - Subsystem: rustc 1.34.2 (6c2484dc3 2019-05-13), cargo 1.34.0 (6789d8a0a 2019-04-01)

## Notes
- I don't have the time at the moment but I can look into writing the validation and checks for test cases within the root if you are busy.

**Comment by calebcartwright** [comment]
Thanks for reporting! I'll take a look and see if I can get this sorted

**Comment by tehstun** [comment]
If it seems misleading or hard to understand just let me know and I will create a demo repository that you can clone. 🐱‍🏍

**Comment by calebcartwright** [comment]
I just made this [sample repo](https://github.com/calebcartwright/rust-test-adapter-test) based on your spec. Does that look right?

**Comment by tehstun** [comment]
main.rs

```rust
#[test]
fn basic_tests() {
    assert_eq!(1 == 2, true);
}

fn main() {}
```

**Comment by calebcartwright** [comment]
Good find on this by the way. I now remember (incorrectly) assuming that on "run all" the Test Explorer API would pass in all the top level node id's under the root vs. just "root". 

I've got a fix in my local env and will publish it here shortly after a bit of testing

**Comment by calebcartwright** [comment]
I've published v0.6.0 to the Marketplace containing a fix for this. When you get a chance @tehstun, give the latest version a try and let me know if it is working for you

**Comment by tehstun** [comment]
@calebcartwright All running and working as expected with the new 0.6.0 version, well done!

psst

![image](https://user-images.githubusercontent.com/12329422/57829909-65f0c600-77a8-11e9-92d9-3278f5a489bc.png)

This would be awesome (debugging a test with LLDB) 😉

**Comment by calebcartwright** [comment]
Closed in https://github.com/swellaby/vscode-rust-test-adapter/commit/0db4ac585bb35eae7e86fb24d37b9641f5a7bd72

**Comment by calebcartwright** [comment]
> This would be awesome (debugging a test with LLDB) 😉

Definitely! It's on [the roadmap](https://github.com/swellaby/vscode-rust-test-adapter/issues/16) but we've still got a little cleanup/refactoring to do first.
