### ISSUE TITLE
`/bin/sh: cargo: command not found`

### ISSUE THREAD

**Issue by Banyc** [swellaby/vscode-rust-test-adapter#329]
I'm using the macOS system. The Rust Explorer Log said:

```text
[...] [INFO] Test Explorer found
[...] [INFO] Initializing Rust adapter
[...] [INFO] Loading Rust Tests
[...] [DEBUG] Unable to parse cargo metadata output. Details: Error: Command failed: cargo metadata --no-deps --format-version 1
/bin/sh: cargo: command not found
```

According to the amount of emojis at <https://github.com/electron/electron/issues/7688#issuecomment-255640358>, it seems like macOS and Linux systems see this problem frequently. The comment provided <https://github.com/sindresorhus/fix-path> as a solution. I don't have an `npm` environment installed so not sure if that will fix the problem but hey according to those emojis...

**Comment by calebcartwright** [comment]
Thanks for reaching out. Can you first confirm that `cargo` is on your path, as detailed in the under the "Configuring the PATH environment variable" section on https://www.rust-lang.org/tools/install? You should be able to do this from any terminal and running something like `cargo --version`

**Comment by Banyc** [comment]
Thanks! Running the install script and then relaunching vscode fixes the problem!
