### ISSUE TITLE
Tests don't appear if  crate-type = cdylib

### ISSUE THREAD

**Issue by ablakey** [swellaby/vscode-rust-test-adapter#34]
I'm very new to Rust so apologies if this is just me misunderstanding things. Thank you for making this plugin. Having a convenient test explorer is a helpful part of learning a new language.

If I run `cargo new --lib foo`  I will get a new library with one test and that test properly shows up in the Test Explorer.

If I add to `cargo.toml`:
```
[lib]
crate-type = ["cdylib"]
```

The tests stop appearing in the Test Explorer.

I am adding that entry because it's what tutorials are telling me to do in order to compile to `wasm`. Details: https://doc.rust-lang.org/stable/edition-guide/rust-2018/platform-and-target-support/cdylib-crates-for-c-interoperability.html

**Comment by calebcartwright** [comment]
> I'm very new to Rust so apologies if this is just me misunderstanding things.

No worries! Thanks for reaching out and providing feedback. 

I've not done any work with web assembly yet myself so I'll need to dig into this. In the meantime, could you let us know what output you get from running the two commands below in your project?

```sh
cargo metadata --no-deps --format-version 1
cargo test -- --list
```

**Comment by ablakey** [comment]
Sure.

```
{"packages":[{"name":"vscode-rust-test-bug-example","version":"0.1.0","id":"vscode-rust-test-bug-example 0.1.0 (path+file:///home/ablakey/repos/vscode-rust-test-bug-example)","license":null,"license_file":null,"description":null,"source":null,"dependencies":[],"targets":[{"kind":["cdylib"],"crate_types":["cdylib"],"name":"vscode-rust-test-bug-example","src_path":"/home/ablakey/repos/vscode-rust-test-bug-example/src/lib.rs","edition":"2018","doctest":false}],"features":{},"manifest_path":"/home/ablakey/repos/vscode-rust-test-bug-example/Cargo.toml","metadata":null,"authors":["Andrew Blakey <ablakey@gmail.com>"],"categories":[],"keywords":[],"readme":null,"repository":null,"edition":"2018","links":null}],"workspace_members":["vscode-rust-test-bug-example 0.1.0 (path+file:///home/ablakey/repos/vscode-rust-test-bug-example)"],"resolve":null,"target_directory":"/home/ablakey/repos/vscode-rust-test-bug-example/target","version":1,"workspace_root":"/home/ablakey/repos/vscode-rust-test-bug-example"}
```

```
cargo  test -- --list
   Compiling vscode-rust-test-bug-example v0.1.0 (/home/ablakey/repos/vscode-rust-test-bug-example)
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running target/debug/deps/vscode_rust_test_bug_example-5b2ff2ace2db1355
tests::it_works: test

1 test, 0 benchmarks
```


I also made this minimal example available here.  https://github.com/ablakey/vscode-rust-test-bug-example

**Comment by calebcartwright** [comment]
Perfect, thanks so much. Will start trying to debug and get back to you when we know more.

**Comment by calebcartwright** [comment]
Okay I see the problem. We're currently only checking for `bin` and `lib` targets in the current pass to load unit tests. However, the target here (and presumably in all wasm projects) is going to be `cdylib` so we need to include `cdylib` in the target check. 

Should be a relatively straightforward fix, will try to have a new/fixed version of the extension ready for you in the next day or two 👍

**Comment by ablakey** [comment]
Wonderful! Thanks for taking the time to look into this. Let me know if I can be of any help.

**Comment by calebcartwright** [comment]
v0.7.0 has been published with a fix. Give it a whirl and let us know if it indeed resolves the issue for you @ablk

**Comment by ablakey** [comment]
Yup this fixes it. Thanks!
