### ISSUE TITLE
Error while debugging test: Error: Method not implemented.

### ISSUE THREAD

**Issue by fengyc** [swellaby/vscode-rust-test-adapter#38]
Not sure it is a bug or not, all test cases of the project could be found in vscode test explorer, but could not be lanuched.

vscode version: 1.37.0
os: win10
rust-toolchain: stable msvc

**Comment by calebcartwright** [comment]
Hi @fengyc, thanks for reaching out. This is expected as we do not (yet) support debugging tests from this extension. 

Adding debug support is on our roadmap via #16. Feel free to track that issue for status on debug support, closing out this one
