### ISSUE TITLE
Support for procedural macro crate

### ISSUE THREAD

**Issue by la10736** [swellaby/vscode-rust-test-adapter#52]
Now if I try to run test in a procedural macro crate I get a "not supported target type" error message in output console log.

My guess is that procedural macro crate are close to lib crate and I don't see real difference from tests point of view.

**Comment by calebcartwright** [comment]
Hi @la10736, thanks for the report! Do you have a sample repo you could share?  

If not, are you able to execute a specific test with a `cargo test -p <<your package name>> --lib <<your test name>>` 

As long as the cargo test commands treat the target like a lib, then all we need to do to support that is determine what the associated target kind is in the cargo metadata output, and then plug that in to the existing list of target kinds that we associate to lib-like for test discovery and execution

https://github.com/swellaby/vscode-rust-test-adapter/blob/ff077f29eb38fcf7d135fdc38d37cc45b5829126/src/cargo.ts#L17

**Comment by la10736** [comment]
You can try on my repo la10736/rstest. Anyway, 

```bash
> cargo init simple_macro --lib
> cd simple_macro
> echo "
[lib]
proc-macro = true
" >> Cargo.toml
```
Now 
```bash
michele@mdamico-laptop:~/sviluppo/simple_macro$ cargo test -p simple_macro
   Compiling simple_macro v0.1.0 (/home/michele/sviluppo/simple_macro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running target/debug/deps/simple_macro-2685b6a517d6dd01

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests simple_macro

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by calebcartwright** [comment]
Thanks! You are correct, we can handle the `proc-macro` target kind like any other lib kind. I'll try to get an updated version of this published to the Marketplace later today

**Comment by calebcartwright** [comment]
@la10736 - v0.9.0 has been published with support for the `proc-macro` target kind. Please give it a try whenever you get an opportunity, and feel free to re-open this if the issue persists.

Thanks again!

**Comment by la10736** [comment]
It works! thank you!
